name: Build `ttf-anonymous-pro-ext`

on:
  push:
    paths:
    - 'ttf-anonymous-pro-ext/**'
    - '.github/workflows/ttf-anonymous-pro-ext.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      uses: jdost/aur@action
      with:
        path: 'ttf-anonymous-pro-ext'
    - uses: actions/upload-artifact@v1
      with:
        name: ttf-anonymous-pro-ext
        path: $(( steps.build.outputs.package }}
